/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dndcombat;

import javax.swing.JFrame;


/**
 *
 * @author icecr
 */
public class LootWindow extends javax.swing.JFrame {

    Model model;
    MainWindow mainWindow;
    
    /**
     * Creates new form LootWindow
     */
    public LootWindow(Model model, MainWindow mainWindow) {
        initComponents();
        this.model = model;
        this.mainWindow = mainWindow;
        
        //Populate party combo box
        for (Player player : model.getParty()) {
            jPartyComboBox.addItem(player.getName());
        }
        
        //Disposes when X button clicked instead of closing whole application
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                //System.out.println("Uncomment following to open another window!");
                //MainPage m = new MainPage();
                //m.setVisible(true);
                e.getWindow().dispose();
                //System.out.println("JFrame Closed!");
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jGoldPanel = new javax.swing.JPanel();
        jGoldAmountTextField = new javax.swing.JTextField();
        jAllocateButton = new javax.swing.JButton();
        jPartyComboBox = new javax.swing.JComboBox<>();
        jDoneButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jGoldAmountTextField.setText("0");

        jAllocateButton.setText("Allocate");
        jAllocateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jAllocateButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jGoldPanelLayout = new javax.swing.GroupLayout(jGoldPanel);
        jGoldPanel.setLayout(jGoldPanelLayout);
        jGoldPanelLayout.setHorizontalGroup(
            jGoldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jGoldPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jGoldAmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jAllocateButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jGoldPanelLayout.setVerticalGroup(
            jGoldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jGoldPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jGoldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jGoldAmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAllocateButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDoneButton.setText("Done");
        jDoneButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDoneButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPartyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jGoldPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jDoneButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jGoldPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jPartyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)))
                .addComponent(jDoneButton)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jDoneButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDoneButtonMouseClicked
        this.dispose();
        mainWindow.refresh();
    }//GEN-LAST:event_jDoneButtonMouseClicked

    private void jAllocateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAllocateButtonMouseClicked
        if (jPartyComboBox.getSelectedIndex() == -1) return;
        if (jGoldAmountTextField.getText().charAt(0) == '-') {
            //TODO: Error dialog box
        }
        
        if (!isInteger(jGoldAmountTextField.getText())) {
            return;
        }
        
        model.getParty().get(jPartyComboBox.getSelectedIndex()).setGold(model.getParty().get(jPartyComboBox.getSelectedIndex()).getGold() + Integer.parseInt(jGoldAmountTextField.getText()));
        jGoldAmountTextField.setText("0");
    }//GEN-LAST:event_jAllocateButtonMouseClicked

    private static boolean isInteger(String string) {
        if (string.isEmpty()) {
            return false;
        }
        char[] characters = string.toCharArray();
        for (char character : characters) {
            if (!(character == '0' || character == '1' || character == '2' || character == '3' || character == '4' || character == '5' || character == '6' || character == '7' || character == '8' || character == '9')) {
                return false;
            }
        }
        return true;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAllocateButton;
    private javax.swing.JButton jDoneButton;
    private javax.swing.JTextField jGoldAmountTextField;
    private javax.swing.JPanel jGoldPanel;
    private javax.swing.JComboBox<String> jPartyComboBox;
    // End of variables declaration//GEN-END:variables
}
