/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dndcombat;

import javax.swing.JFrame;

/**
 *
 * @author icecr
 */
public class NewPlayerWindow extends javax.swing.JFrame {

    Model model;
    MainWindow mainWindow;

    /**
     * Creates new form NewPlayerWindow
     */
    public NewPlayerWindow(Model model, MainWindow mainWindow) {
        initComponents();
        this.model = model;
        this.mainWindow = mainWindow;

        //Disposes when X button clicked instead of closing whole application
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                //System.out.println("Uncomment following to open another window!");
                //MainPage m = new MainPage();
                //m.setVisible(true);
                e.getWindow().dispose();
                //System.out.println("JFrame Closed!");
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCharacterNameLabel = new javax.swing.JLabel();
        jCharacterNameTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jClassComboBox = new javax.swing.JComboBox<>();
        jDoneButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jArmorClassTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jStrengthTextField = new javax.swing.JTextField();
        jDexterityTextField = new javax.swing.JTextField();
        jConstitutionTextField = new javax.swing.JTextField();
        jIntelligenceTextField = new javax.swing.JTextField();
        jWisdomTextField = new javax.swing.JTextField();
        jCharismaTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jMaximumHealthTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jRaceComboBox = new javax.swing.JComboBox<>();
        jErrorOutputLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jCharacterNameLabel.setText("Character Name:");

        jLabel1.setText("Class:");

        jClassComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Barbarian", "Bard", "Cleric", "Druid", "Fighter", "Monk", "Paladin", "Ranger", "Rogue", "Sorcerer", "Warlock", "Wizard" }));

        jDoneButton.setText("Done");
        jDoneButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDoneButtonMouseClicked(evt);
            }
        });

        jLabel2.setText("Armor Class:");

        jLabel3.setText("Strength:");

        jLabel4.setText("Dexterity:");

        jLabel5.setText("Constitution:");

        jLabel6.setText("Intelligence:");

        jLabel7.setText("Wisdom:");

        jLabel8.setText("Charisma:");

        jLabel9.setText("Maximum Health:");

        jLabel10.setText("Race:");

        jRaceComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dragonborn", "Dwarf", "Elf", "Gnome", "Half-Elf", "Halfling", "Half-Orc", "Human", "Tiefling", "Aarakocra", "Genasi", "Goliath", " " }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jMaximumHealthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jErrorOutputLabel))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jArmorClassTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCharacterNameLabel)
                            .addComponent(jLabel1)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRaceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jClassComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCharacterNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jConstitutionTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jIntelligenceTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jWisdomTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCharismaTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jStrengthTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDexterityTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jDoneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(181, 181, 181))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCharacterNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCharacterNameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jClassComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jRaceComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jMaximumHealthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jArmorClassTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jStrengthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jDexterityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jConstitutionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jIntelligenceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jWisdomTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jCharismaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jErrorOutputLabel)
                .addGap(1, 1, 1)
                .addComponent(jDoneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jDoneButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDoneButtonMouseClicked
        String name = jCharacterNameTextField.getText();
        if (jCharacterNameTextField.getText().isEmpty()) {
            jErrorOutputLabel.setText("Please input a name!");
            return;
        }

        String playerClass = jClassComboBox.getSelectedItem().toString();
        String race = jRaceComboBox.getSelectedItem().toString();

        int maxHealth = 0;
        if (isInteger(jMaximumHealthTextField.getText())) {
            maxHealth = Integer.parseInt(jMaximumHealthTextField.getText());
        } else {
            jErrorOutputLabel.setText("Improper maximum health! Input an integer");
            return;
        }

        int armorClass = 0;
        if (isInteger(jArmorClassTextField.getText())) {
            armorClass = Integer.parseInt(jArmorClassTextField.getText());
        } else {
            jErrorOutputLabel.setText("Improper armor class! Input an integer");
            return;
        }

        int strength = 0;
        if (isInteger(jStrengthTextField.getText())) {
            strength = Integer.parseInt(jStrengthTextField.getText());
        } else {
            jErrorOutputLabel.setText("Improper strength! Input an integer");
            return;
        }

        int dexterity = 0;
        if (isInteger(jDexterityTextField.getText())) {
            dexterity = Integer.parseInt(jDexterityTextField.getText());
        } else {
            jErrorOutputLabel.setText("Improper dexterity! Input an integer");
            return;
        }

        int constitution = 0;
        if (isInteger(jConstitutionTextField.getText())) {
            constitution = Integer.parseInt(jConstitutionTextField.getText());
        } else {
            jErrorOutputLabel.setText("Improper constitution! Input an integer");
            return;
        }

        int intelligence = 0;
        if (isInteger(jIntelligenceTextField.getText())) {
            intelligence = Integer.parseInt(jIntelligenceTextField.getText());
        } else {
            jErrorOutputLabel.setText("Improper intelligence! Input an integer");
            return;
        }

        int wisdom = 0;
        if (isInteger(jWisdomTextField.getText())) {
            wisdom = Integer.parseInt(jWisdomTextField.getText());
        } else {
            jErrorOutputLabel.setText("Improper wisdom! Input an integer");
            return;
        }

        int charisma = 0;
        if (isInteger(jCharismaTextField.getText())) {
            charisma = Integer.parseInt(jCharismaTextField.getText());
        } else {
            jErrorOutputLabel.setText("Improper charisma! Input an integer");
            return;
        }

        model.addPartyMember(new Player(name, playerClass, race, maxHealth, armorClass, strength, dexterity, constitution, intelligence, wisdom, charisma));
        this.dispose();
        mainWindow.refresh();
    }//GEN-LAST:event_jDoneButtonMouseClicked

    private static boolean isInteger(String string) {
        if (string.isEmpty()) {
            return false;
        }
        char[] characters = string.toCharArray();
        for (char character : characters) {
            if (!(character == '0' || character == '1' || character == '2' || character == '3' || character == '4' || character == '5' || character == '6' || character == '7' || character == '8' || character == '9')) {
                return false;
            }
        }
        return true;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jArmorClassTextField;
    private javax.swing.JLabel jCharacterNameLabel;
    private javax.swing.JTextField jCharacterNameTextField;
    private javax.swing.JTextField jCharismaTextField;
    private javax.swing.JComboBox<String> jClassComboBox;
    private javax.swing.JTextField jConstitutionTextField;
    private javax.swing.JTextField jDexterityTextField;
    private javax.swing.JButton jDoneButton;
    private javax.swing.JLabel jErrorOutputLabel;
    private javax.swing.JTextField jIntelligenceTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jMaximumHealthTextField;
    private javax.swing.JComboBox<String> jRaceComboBox;
    private javax.swing.JTextField jStrengthTextField;
    private javax.swing.JTextField jWisdomTextField;
    // End of variables declaration//GEN-END:variables
}
